# Generated by Django 4.2.7 on 2023-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='username'),
        ),
    ]
