# Generated by Django 4.2.7 on 2023-12-04 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('total_likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 4, 7, 1, 6, 743922, tzinfo=datetime.timezone.utc))),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
