# Generated by Django 4.2.7 on 2023-12-04 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_delete_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 7, 3, 46, 965246, tzinfo=datetime.timezone.utc)),
        ),
    ]
