# Generated by Django 4.2.7 on 2023-12-27 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_post_created_at_alter_userlikepost_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 14, 34, 26, 926729, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlikepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 14, 34, 26, 927846, tzinfo=datetime.timezone.utc)),
        ),
    ]
