# Generated by Django 4.2.7 on 2023-12-27 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_post_created_at_alter_userlikepost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 14, 49, 4, 413451, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlikepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 14, 49, 4, 414719, tzinfo=datetime.timezone.utc)),
        ),
    ]
