# Generated by Django 4.2.7 on 2023-12-30 03:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_alter_post_created_at_alter_userlikepost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 3, 43, 23, 861381, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlikepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 3, 43, 23, 863358, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=300, verbose_name='First name of user')),
                ('last_name', models.CharField(blank=True, max_length=300, verbose_name='Last name of user')),
                ('occupation', models.CharField(blank=True, max_length=300, verbose_name='Occupation of user')),
                ('status', models.CharField(blank=True, max_length=600, verbose_name='Current status of user')),
                ('location', models.CharField(blank=True, max_length=600, verbose_name='location of user')),
                ('home_address', models.TextField(blank=True, verbose_name='Complete home address of user')),
                ('phone_number', models.CharField(blank=True, max_length=10, verbose_name='Phone number of user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(verbose_name='Introduction about the user')),
                ('education', models.CharField(blank=True, max_length=500, verbose_name='Name of the college')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Date of birth')),
                ('organization', models.CharField(blank=True, max_length=500, verbose_name='Organization name in which currently working.')),
                ('nationality', models.CharField(choices=[('Eritrea', 'Eritrea'), ('Samoa', 'Samoa'), ('North Macedonia', 'North Macedonia'), ('Djibouti', 'Djibouti'), ('Jordan', 'Jordan'), ('Pakistan', 'Pakistan'), ('Ireland', 'Ireland'), ('Mauritania', 'Mauritania'), ('Denmark', 'Denmark'), ('Namibia', 'Namibia'), ('Ghana', 'Ghana'), ('South Sudan', 'South Sudan'), ('Slovakia', 'Slovakia'), ('Moldova', 'Moldova'), ('North Korea', 'North Korea'), ('Seychelles', 'Seychelles'), ('Armenia', 'Armenia'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Syria', 'Syria'), ('Angola', 'Angola'), ('Tajikistan', 'Tajikistan'), ('Venezuela', 'Venezuela'), ('Poland', 'Poland'), ('Saudi Arabia', 'Saudi Arabia'), ('Republic of the Congo', 'Republic of the Congo'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('San Marino', 'San Marino'), ('Czechia', 'Czechia'), ('Guatemala', 'Guatemala'), ('South Korea', 'South Korea'), ('Estonia', 'Estonia'), ('Nepal', 'Nepal'), ('Botswana', 'Botswana'), ('Philippines', 'Philippines'), ('Iraq', 'Iraq'), ('Lebanon', 'Lebanon'), ('Burundi', 'Burundi'), ('Mongolia', 'Mongolia'), ('Paraguay', 'Paraguay'), ('Algeria', 'Algeria'), ('France', 'France'), ('Netherlands', 'Netherlands'), ('Chad', 'Chad'), ('Finland', 'Finland'), ('Panama', 'Panama'), ('Yemen', 'Yemen'), ('Brazil', 'Brazil'), ('Nigeria', 'Nigeria'), ('Palau', 'Palau'), ('Japan', 'Japan'), ('Tanzania', 'Tanzania'), ('Kazakhstan', 'Kazakhstan'), ('Portugal', 'Portugal'), ('Sri Lanka', 'Sri Lanka'), ('Germany', 'Germany'), ('Myanmar', 'Myanmar'), ('Colombia', 'Colombia'), ('Peru', 'Peru'), ('Senegal', 'Senegal'), ('Kyrgyzstan', 'Kyrgyzstan'), ('China', 'China'), ('Afghanistan', 'Afghanistan'), ('Turkey', 'Turkey'), ('Liberia', 'Liberia'), ('South Africa', 'South Africa'), ('Chile', 'Chile'), ('Malta', 'Malta'), ('Kiribati', 'Kiribati'), ('Cape Verde', 'Cape Verde'), ('Iceland', 'Iceland'), ('Gambia', 'Gambia'), ('Vanuatu', 'Vanuatu'), ('Uruguay', 'Uruguay'), ('Oman', 'Oman'), ('Sudan', 'Sudan'), ('India', 'India'), ('Laos', 'Laos'), ('Comoros', 'Comoros'), ('Spain', 'Spain'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Uzbekistan', 'Uzbekistan'), ('Maldives', 'Maldives'), ('Indonesia', 'Indonesia'), ('Vietnam', 'Vietnam'), ('Malaysia', 'Malaysia'), ('Eswatini', 'Eswatini'), ('Uganda', 'Uganda'), ('Madagascar', 'Madagascar'), ('Fiji', 'Fiji'), ('Norway', 'Norway'), ('Cyprus', 'Cyprus'), ('Papua New Guinea', 'Papua New Guinea'), ('Rwanda', 'Rwanda'), ('DR Congo', 'DR Congo'), ('Cameroon', 'Cameroon'), ('Serbia', 'Serbia'), ('Lithuania', 'Lithuania'), ('Cambodia', 'Cambodia'), ('United Arab Emirates', 'United Arab Emirates'), ('Monaco', 'Monaco'), ('Cuba', 'Cuba'), ('Togo', 'Togo'), ('Luxembourg', 'Luxembourg'), ('Mauritius', 'Mauritius'), ('Argentina', 'Argentina'), ('Grenada', 'Grenada'), ('Nicaragua', 'Nicaragua'), ('Ukraine', 'Ukraine'), ('Guyana', 'Guyana'), ('Niger', 'Niger'), ('Benin', 'Benin'), ('Saint Lucia', 'Saint Lucia'), ('Tuvalu', 'Tuvalu'), ('Egypt', 'Egypt'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Lesotho', 'Lesotho'), ('Tonga', 'Tonga'), ('Georgia', 'Georgia'), ('Ethiopia', 'Ethiopia'), ('Dominican Republic', 'Dominican Republic'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Belize', 'Belize'), ('Morocco', 'Morocco'), ('Haiti', 'Haiti'), ('Burkina Faso', 'Burkina Faso'), ('Bangladesh', 'Bangladesh'), ('Kuwait', 'Kuwait'), ('Jamaica', 'Jamaica'), ('Romania', 'Romania'), ('São Tomé and Príncipe', 'São Tomé and Príncipe'), ('Bahamas', 'Bahamas'), ('Mexico', 'Mexico'), ('El Salvador', 'El Salvador'), ('Micronesia', 'Micronesia'), ('Turkmenistan', 'Turkmenistan'), ('Central African Republic', 'Central African Republic'), ('Suriname', 'Suriname'), ('Belgium', 'Belgium'), ('Sweden', 'Sweden'), ('Bolivia', 'Bolivia'), ('Montenegro', 'Montenegro'), ('Mozambique', 'Mozambique'), ('Latvia', 'Latvia'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Vatican City', 'Vatican City'), ('Austria', 'Austria'), ('Albania', 'Albania'), ('Zambia', 'Zambia'), ('Liechtenstein', 'Liechtenstein'), ('Qatar', 'Qatar'), ('Solomon Islands', 'Solomon Islands'), ('Nauru', 'Nauru'), ('Greece', 'Greece'), ('Libya', 'Libya'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Barbados', 'Barbados'), ('Honduras', 'Honduras'), ('Somalia', 'Somalia'), ('Italy', 'Italy'), ('Andorra', 'Andorra'), ('Ecuador', 'Ecuador'), ('Kenya', 'Kenya'), ('Bahrain', 'Bahrain'), ('United Kingdom', 'United Kingdom'), ('Guinea', 'Guinea'), ('Russia', 'Russia'), ('Brunei', 'Brunei'), ('Zimbabwe', 'Zimbabwe'), ('Australia', 'Australia'), ('Slovenia', 'Slovenia'), ('Belarus', 'Belarus'), ('Thailand', 'Thailand'), ('New Zealand', 'New Zealand'), ('Tunisia', 'Tunisia'), ('Marshall Islands', 'Marshall Islands'), ('Sierra Leone', 'Sierra Leone'), ('Bhutan', 'Bhutan'), ('United States', 'United States'), ('Switzerland', 'Switzerland'), ('Gabon', 'Gabon'), ('Dominica', 'Dominica'), ('Canada', 'Canada'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Singapore', 'Singapore'), ('Hungary', 'Hungary'), ('Costa Rica', 'Costa Rica'), ('Israel', 'Israel'), ('Bulgaria', 'Bulgaria'), ('Azerbaijan', 'Azerbaijan'), ('Timor-Leste', 'Timor-Leste'), ('Iran', 'Iran'), ('Croatia', 'Croatia'), ('Ivory Coast', 'Ivory Coast')], max_length=300, verbose_name='Nationality of the user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
