# Generated by Django 4.2.7 on 2023-12-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_hobby_skill_generalinformation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
