# Generated by Django 4.2.7 on 2023-12-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_generalinformation_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='Introduction about the user'),
        ),
    ]
