# Generated by Django 4.2.7 on 2023-12-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_personalinformation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Profile pic of user'),
        ),
    ]
