# Generated by Django 4.2.7 on 2024-01-29 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_personalinformation_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='nationality',
            field=models.CharField(choices=[('Andorra', 'Andorra'), ('Laos', 'Laos'), ('Canada', 'Canada'), ('Nigeria', 'Nigeria'), ('Vanuatu', 'Vanuatu'), ('Czechia', 'Czechia'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Iceland', 'Iceland'), ('Norway', 'Norway'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Chile', 'Chile'), ('Kuwait', 'Kuwait'), ('Dominica', 'Dominica'), ('Montenegro', 'Montenegro'), ('Cameroon', 'Cameroon'), ('Sri Lanka', 'Sri Lanka'), ('China', 'China'), ('Bangladesh', 'Bangladesh'), ('Sweden', 'Sweden'), ('Grenada', 'Grenada'), ('Turkey', 'Turkey'), ('Guinea', 'Guinea'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Singapore', 'Singapore'), ('Morocco', 'Morocco'), ('Iraq', 'Iraq'), ('Brunei', 'Brunei'), ('North Korea', 'North Korea'), ('Iran', 'Iran'), ('Paraguay', 'Paraguay'), ('Albania', 'Albania'), ('Tajikistan', 'Tajikistan'), ('Bolivia', 'Bolivia'), ('Austria', 'Austria'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Colombia', 'Colombia'), ('Belize', 'Belize'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Marshall Islands', 'Marshall Islands'), ('Myanmar', 'Myanmar'), ('Brazil', 'Brazil'), ('Croatia', 'Croatia'), ('Somalia', 'Somalia'), ('Afghanistan', 'Afghanistan'), ('New Zealand', 'New Zealand'), ('Eritrea', 'Eritrea'), ('Cambodia', 'Cambodia'), ('Bahamas', 'Bahamas'), ('Belarus', 'Belarus'), ('Tuvalu', 'Tuvalu'), ('Mauritania', 'Mauritania'), ('Bulgaria', 'Bulgaria'), ('Mozambique', 'Mozambique'), ('Estonia', 'Estonia'), ('Italy', 'Italy'), ('Malta', 'Malta'), ('Slovenia', 'Slovenia'), ('India', 'India'), ('Peru', 'Peru'), ('Burundi', 'Burundi'), ('Lithuania', 'Lithuania'), ('United States', 'United States'), ('Honduras', 'Honduras'), ('Tonga', 'Tonga'), ('Saudi Arabia', 'Saudi Arabia'), ('Suriname', 'Suriname'), ('Qatar', 'Qatar'), ('Mauritius', 'Mauritius'), ('Barbados', 'Barbados'), ('Syria', 'Syria'), ('Egypt', 'Egypt'), ('São Tomé and Príncipe', 'São Tomé and Príncipe'), ('Kiribati', 'Kiribati'), ('Timor-Leste', 'Timor-Leste'), ('Lesotho', 'Lesotho'), ('Solomon Islands', 'Solomon Islands'), ('Libya', 'Libya'), ('South Korea', 'South Korea'), ('Liechtenstein', 'Liechtenstein'), ('Nicaragua', 'Nicaragua'), ('Ecuador', 'Ecuador'), ('Maldives', 'Maldives'), ('Algeria', 'Algeria'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Finland', 'Finland'), ('Kenya', 'Kenya'), ('Cuba', 'Cuba'), ('Poland', 'Poland'), ('Ethiopia', 'Ethiopia'), ('Togo', 'Togo'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Uruguay', 'Uruguay'), ('Cape Verde', 'Cape Verde'), ('Chad', 'Chad'), ('Vatican City', 'Vatican City'), ('Palau', 'Palau'), ('Haiti', 'Haiti'), ('Yemen', 'Yemen'), ('Eswatini', 'Eswatini'), ('Zimbabwe', 'Zimbabwe'), ('Greece', 'Greece'), ('Israel', 'Israel'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Cyprus', 'Cyprus'), ('Monaco', 'Monaco'), ('Fiji', 'Fiji'), ('Ukraine', 'Ukraine'), ('Portugal', 'Portugal'), ('Bhutan', 'Bhutan'), ('Nepal', 'Nepal'), ('France', 'France'), ('Ireland', 'Ireland'), ('United Arab Emirates', 'United Arab Emirates'), ('Saint Lucia', 'Saint Lucia'), ('Dominican Republic', 'Dominican Republic'), ('Serbia', 'Serbia'), ('Botswana', 'Botswana'), ('Ivory Coast', 'Ivory Coast'), ('Ghana', 'Ghana'), ('Comoros', 'Comoros'), ('Azerbaijan', 'Azerbaijan'), ('United Kingdom', 'United Kingdom'), ('Central African Republic', 'Central African Republic'), ('San Marino', 'San Marino'), ('Djibouti', 'Djibouti'), ('Denmark', 'Denmark'), ('Papua New Guinea', 'Papua New Guinea'), ('Madagascar', 'Madagascar'), ('Hungary', 'Hungary'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Gambia', 'Gambia'), ('Luxembourg', 'Luxembourg'), ('Republic of the Congo', 'Republic of the Congo'), ('Argentina', 'Argentina'), ('DR Congo', 'DR Congo'), ('Jordan', 'Jordan'), ('Belgium', 'Belgium'), ('Switzerland', 'Switzerland'), ('Indonesia', 'Indonesia'), ('Lebanon', 'Lebanon'), ('Malaysia', 'Malaysia'), ('Slovakia', 'Slovakia'), ('Armenia', 'Armenia'), ('Mongolia', 'Mongolia'), ('Japan', 'Japan'), ('South Africa', 'South Africa'), ('Philippines', 'Philippines'), ('Micronesia', 'Micronesia'), ('Germany', 'Germany'), ('Latvia', 'Latvia'), ('Jamaica', 'Jamaica'), ('Nauru', 'Nauru'), ('Guyana', 'Guyana'), ('Burkina Faso', 'Burkina Faso'), ('Sudan', 'Sudan'), ('Russia', 'Russia'), ('Australia', 'Australia'), ('Liberia', 'Liberia'), ('Mexico', 'Mexico'), ('Tunisia', 'Tunisia'), ('Kazakhstan', 'Kazakhstan'), ('Oman', 'Oman'), ('Niger', 'Niger'), ('Turkmenistan', 'Turkmenistan'), ('Sierra Leone', 'Sierra Leone'), ('Samoa', 'Samoa'), ('Senegal', 'Senegal'), ('Georgia', 'Georgia'), ('Namibia', 'Namibia'), ('South Sudan', 'South Sudan'), ('Thailand', 'Thailand'), ('Bahrain', 'Bahrain'), ('Vietnam', 'Vietnam'), ('Guatemala', 'Guatemala'), ('Moldova', 'Moldova'), ('North Macedonia', 'North Macedonia'), ('Uzbekistan', 'Uzbekistan'), ('Romania', 'Romania'), ('Uganda', 'Uganda'), ('El Salvador', 'El Salvador'), ('Zambia', 'Zambia'), ('Gabon', 'Gabon'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Spain', 'Spain'), ('Netherlands', 'Netherlands'), ('Benin', 'Benin'), ('Pakistan', 'Pakistan'), ('Panama', 'Panama'), ('Angola', 'Angola'), ('Venezuela', 'Venezuela'), ('Costa Rica', 'Costa Rica'), ('Seychelles', 'Seychelles')], max_length=300, verbose_name='Nationality of the user'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_status', models.BooleanField(default=True)),
                ('Accept_status', models.BooleanField(default=False)),
                ('Declined_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
