# Generated by Django 4.2.7 on 2024-01-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_generalinformation_nationality_friendrequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='Accept_status',
            new_name='accept_status',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='Declined_status',
            new_name='declined_status',
        ),
    ]
